.\Alu\alu.v 
.\Alu\alu_op.v 
.\Alu\Adder\adder_32.v 
.\Alu\Adder\adder_8.v 
.\Alu\Adder\cla_32.v 
.\Alu\Adder\cla_8.v 
.\Alu\Adder\full_adder.v 
.\Alu\Comparators\comparator_2.v 
.\Alu\Comparators\comparator_32.v 
.\Alu\Comparators\comparator_8.v 
.\Alu\Logical\and_32.v 
.\Alu\Logical\not_32.v 
.\Alu\Logical\or_32.v 
.\Alu\Shifter\barrel_left_1.v 
.\Alu\Shifter\barrel_left_16.v 
.\Alu\Shifter\barrel_left_2.v 
.\Alu\Shifter\barrel_left_4.v 
.\Alu\Shifter\barrel_left_8.v 
.\Alu\Shifter\barrel_right_1.v 
.\Alu\Shifter\barrel_right_16.v 
.\Alu\Shifter\barrel_right_2.v 
.\Alu\Shifter\barrel_right_4.v 
.\Alu\Shifter\barrel_right_8.v 
.\Alu\Shifter\shift_left_32.v 
.\Alu\Shifter\shift_right_32.v 
.\MultDiv\checkBits_32.v 
.\MultDiv\multdiv.v 
.\MultDiv\resetDetection.v 
.\MultDiv\Div\counter_32.v 
.\MultDiv\Div\div.v 
.\MultDiv\Div\divControl.v 
.\MultDiv\Mult\counter_16.v 
.\MultDiv\Mult\mult.v 
.\MultDiv\Mult\multControl.v 
.\MultDiv\Mult\specialCaseCheck.v 
.\MultDiv\Mux\mux_2_65.v 
.\MultDiv\Mux\mux_4_65.v 
.\Mux\decoder_32.v 
.\Mux\mux_2.v 
.\Mux\mux_2_1.v 
.\Mux\mux_32.v 
.\Mux\mux_4.v 
.\Mux\mux_8.v 
.\Processor\processor.v 
.\Processor\RAM.v 
.\Processor\ROM.v 
.\Processor\Wrapper.v 
.\Processor\control\control.v 
.\Processor\Latches\DX.v 
.\Processor\Latches\FD.v 
.\Processor\Latches\MW.v 
.\Processor\Latches\PC.v 
.\Processor\Latches\XM.v 
.\Processor\Provided-Behavioral-Components\divider_ref.v 
.\Register\dffe_ref.v 
.\Register\regfile.v 
.\Register\register_32.v 
.\Register\register_65.v 
.\Register\tri_state32.v 
.\Register\t_flip_flop.v 
