.\Alu\alu.v 
.\Alu\alu_op.v 
.\Alu\Adder\adder_32.v 
.\Alu\Adder\adder_8.v 
.\Alu\Adder\cla_32.v 
.\Alu\Adder\cla_8.v 
.\Alu\Adder\full_adder.v 
.\Alu\Comparators\comparator_2.v 
.\Alu\Comparators\comparator_32.v 
.\Alu\Comparators\comparator_8.v 
.\Alu\Logical\and_32.v 
.\Alu\Logical\not_32.v 
.\Alu\Logical\or_32.v 
.\Alu\Shifter\barrel_left_1.v 
.\Alu\Shifter\barrel_left_16.v 
.\Alu\Shifter\barrel_left_2.v 
.\Alu\Shifter\barrel_left_4.v 
.\Alu\Shifter\barrel_left_8.v 
.\Alu\Shifter\barrel_right_1.v 
.\Alu\Shifter\barrel_right_16.v 
.\Alu\Shifter\barrel_right_2.v 
.\Alu\Shifter\barrel_right_4.v 
.\Alu\Shifter\barrel_right_8.v 
.\Alu\Shifter\shift_left_32.v 
.\Alu\Shifter\shift_right_32.v 
.\Mux\mux_2.v 
.\Mux\mux_2_1bit.v 
.\Mux\mux_32.v 
.\Mux\mux_4.v 
.\Mux\mux_8.v 
