.\Alu\alu.v 
.\Alu\alu_op.v 
.\Alu\Adder\adder_32.v 
.\Alu\Adder\adder_8.v 
.\Alu\Adder\cla_32.v 
.\Alu\Adder\cla_8.v 
.\Alu\Adder\full_adder.v 
.\Alu\Adder\twos_comp.v 
.\Alu\Comparators\comparator_2.v 
.\Alu\Comparators\comparator_32.v 
.\Alu\Comparators\comparator_8.v 
.\Alu\Logical\and_32.v 
.\Alu\Logical\not_32.v 
.\Alu\Logical\or_32.v 
.\Alu\Shifter\barrel_left_1.v 
.\Mux\mux_2.v 
.\Mux\mux_32.v 
.\Mux\mux_4.v 
.\Mux\mux_8.v 
