# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.runs/synth_1/.Xil/Vivado-37428-NRG-Laptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.srcs/sources_1/ip/ila_0/hdl/verilog
    {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Tests/CPU Test Files/Memory Files}
  } {
      C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.srcs/sources_1/ip/ila_0/hdl/verilog
    {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Tests/CPU Test Files/Memory Files}
  } {
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.runs/synth_1/.Xil/Vivado-37428-NRG-Laptop/realtime/ila_0_stub.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Audio/AudioController.v
      {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Seven Segment/BCD.v}
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Latches/DX.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Latches/FD.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Latches/MW.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Latches/PC.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/PCControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Audio/PWMDeserializer.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Audio/PWMSerializer.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/RAM.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/ROM.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Timer.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Latches/XM.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Adder/adder_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Adder/adder_8.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/alu.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/alu_op.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Logical/and_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_left_1.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_left_16.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_left_2.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_left_4.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_left_8.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_right_1.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_right_16.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_right_2.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_right_4.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/barrel_right_8.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Button/buttonHandler.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Hazard/bypass.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/checkBits_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Adder/cla_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Adder/cla_8.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/clockDivider.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Comparators/comparator_2.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Comparators/comparator_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Comparators/comparator_8.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Mult/counter_16.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Div/counter_32.v
      {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Seven Segment/counter_4.v}
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Button/debounce.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/decodeControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/decoder_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Register/dffe_ref.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Div/div.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Div/divControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/exception.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/executeControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/sign-extention/extend_16.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Adder/full_adder.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Hazard/interlock.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/memoryControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Mult/mult.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Mult/multControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/multDivStall.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/multdiv.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/mux_2.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/mux_2_1.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/mux_2_5.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Mux/mux_2_65.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/mux_4.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/mux_4_5.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Mux/mux_4_65.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Mux/mux_8.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Logical/not_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Logical/or_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/processor.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/pulse.v
      {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Seven Segment/regToSegment.v}
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Register/regfile.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Register/register_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Register/register_65.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/resetDetection.v
      {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Seven Segment/segmentWrapper.v}
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/shift_left_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Alu/Shifter/shift_right_32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/MultDiv/Mult/specialCaseCheck.v
      {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/IO/Seven Segment/switchToSegmentDebug.v}
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Register/t_flip_flop.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Register/tri_state32.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/type_detector.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/control/writebackControl.v
      C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/Processor/Wrapper.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.runs/synth_1/.Xil/Vivado-37428-NRG-Laptop/realtime/Wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top Wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/vivado.runs/synth_1/.Xil/Vivado-37428-NRG-Laptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
