@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Mar 31 11:22:00 -0400 2023
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Wrapper_tb_time_impl -key {Post-Implementation:sim_1:Timing:Wrapper_tb} -tclbatch Wrapper_tb.tcl -view C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/Wrapper_tb_time_impl.wcfg -log simulate.log"
call xsim  Wrapper_tb_time_impl -key {Post-Implementation:sim_1:Timing:Wrapper_tb} -tclbatch Wrapper_tb.tcl -view C:/Users/nolan/Duke/ece350/ece350-32bit-cpu/vivado/Wrapper_tb_time_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
